# Enhanced ansible-lint configuration for kaitranntt.mac collection

# Exclude paths from linting
exclude_paths:
- .git/
- .pytest_cache/
- .molecule/
- '*.tar.gz'
- tests/molecule/**/created/

# Skip specific rules temporarily
skip_list:
- '106'    # Role name {} does not match ``^[a-z][a-z0-9_]+$`` pattern
- '208'    # File permissions not mentioned
- fqcn[action-core]      # Allow short module names for core modules
- fqcn[action]           # Allow short module names for common modules
- name[template]         # Allow Jinja2 templates in names
- yaml[octal-values]     # Allow octal values where needed

# Warning list for experimental rules
warn_list:
- experimental           # Enable experimental rules
- jinja[spacing]          # Jinja2 spacing warnings
- name[imperative]        # Use imperative mood in task names
- no-loop-var-prefix     # Loop variable naming
- '501'                  # No 'loops' should be used
- '502'                  # All tasks should be named
- '503'                  # Tasks that run when changed should likely be handlers
- '504'                  # Do not check 'galaxy_info' for versions
- '301'                  # Commands should not be used in place of modules
- '305'                  # Use shell only when shell functionality is required
- '401'                  # Git checkouts must contain explicit version
- '403'                  # Package installs should not use latest
- '404'                  # Doesn't need a restart for service

# Enable specific additional rules
enable_list:
- yaml-empty-lines
- yaml-trailing-spaces
- yaml-trailing-newlines
- var-naming[no-role-prefix]

# General configuration
offline: true
parseable: true
quiet: false
strict: true

# Custom rules directory
rulesdir:
- .ansible-lint-rules/

# Loop variable prefix configuration
loop_var_prefix: "{{ role_name | regex_replace('-', '_') }}_"

# Use default rules
use_default_rules: true

# Tags for focused checking
tags:
- format
- idempotency
- security
- syntax
- deprecations
