extends: default

rules:
  line-length:
    max: 120
  document-start:
    present: false
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  trailing-spaces: enable
  new-line-at-end-of-file: enable

ignore: |
  .git/
  .molecule/
  tests/molecule/**/created/
  *.tar.gz
  .pytest_cache/
  .cache/
  .venv/
  venv/
  __pycache__/
  *.pyc
  .coverage
  htmlcov/
