version: '3.8'

services:
  macos-test:
    image: dockurr/macos
    container_name: macos-test-${TEST_ID:-local}
    environment:
      VERSION: "${MACOS_VERSION:-14}"
      DISK_SIZE: "${DISK_SIZE:-64G}"
      RAM_SIZE: "${RAM_SIZE:-8G}"
      CPU_CORES: "${CPU_CORES:-4}"
      DEVICE_MODEL: "Macmini8,1"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "${WEB_PORT:-8006}:8006"
      - "${VNC_PORT:-5900}:5900"
      - "${SSH_PORT:-2222}:22"
    volumes:
      - ./test-artifacts/${TEST_ID:-local}:/storage
      - ./scripts:/workspace/scripts:ro
      - ./tests:/workspace/tests:ro
      - ./roles:/workspace/roles:ro
    networks:
      - macos-test-net
    stop_timeout: 120
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8006 || true"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s
    tmpfs:
      - /tmp
      - /var/tmp
    command: []
    privileged: true

networks:
  macos-test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
