# macOS-specific variables for Tailscale

# macOS architecture detection
tailscale_arch: "{{ 'arm64' if ansible_architecture == 'arm64' or ansible_architecture
  == 'aarch64' else 'x86_64' }}"

# Tailscale download URL based on architecture
tailscale_download_url: '{{ tailscale_base_url }}macos/tailscale_{{ tailscale_arch
  }}.zip'

# Temporary directory for installation
tailscale_temp_dir: /tmp/tailscale_install_{{ ansible_date_time.epoch }}

# Tailscale installation paths
tailscale_install_dir: /usr/local/bin
tailscale_daemon_path: /usr/local/bin/tailscaled

# macOS service paths
tailscale_service_plist_path: 
  /Library/LaunchDaemons/com.tailscale.tailscaled.plist
tailscale_service_plist_template: com.tailscale.tailscaled.plist.j2

# macOS system paths
tailscale_socket_path: /var/run/tailscale/tailscaled.sock
tailscale_log_file: /var/log/tailscaled.log

# Required packages for Tailscale on macOS
tailscale_required_packages: []

# macOS version compatibility
tailscale_min_macos_version: '11.0'
tailscale_supported_versions:
- '11.0'
- '11.1'
- '11.2'
- '11.3'
- '11.4'
- '11.5'
- '11.6'
- '11.7'
- '12.0'
- '12.1'
- '12.2'
- '12.3'
- '12.4'
- '12.5'
- '12.6'
- '12.7'
- '13.0'
- '13.1'
- '13.2'
- '13.3'
- '13.4'
- '13.5'
- '13.6'
- '14.0'
- '14.1'
- '14.2'
- '14.3'
- '14.4'
- '14.5'
- '14.6'
- '15.0'
- '15.1'
- '15.2'

# Tailscale service configuration
tailscale_service_name: com.tailscale.tailscaled

# Installation paths
tailscale_cli_path: '{{ tailscale_binary_path }}'
tailscaled_cli_path: '{{ tailscaled_binary_path }}'

# Package architecture mapping
tailscale_arch_map:
  x86_64: amd64
  arm64: arm64

# Download URL patterns
tailscale_download_patterns:
  go: >-
    https://pkgs.tailscale.com/stable/tailscale_{{ tailscale_version }}_{{
    tailscale_arch_map[ansible_architecture] }}.tar.gz
  binary: >-
    https://pkgs.tailscale.com/stable/tailscale_{{ tailscale_version }}_{{
    tailscale_arch_map[ansible_architecture] }}.tar.gz
  homebrew: tailscale/tap/tailscale

# Log levels
tailscale_log_levels:
- debug
- info
- warn
- error

# State management
tailscale_state_map:
  present: install
  absent: remove

# Default network timeout values
tailscale_timeouts:
  auth: 30
  connect: 60
  status: 10
  service_start: 30
