# Handlers for Tailscale role

- name: restart tailscale
  ansible.builtin.command: launchctl kickstart -k
    system/com.tailscale.tailscaled
  become: true
  changed_when: false
  listen: restart tailscale

- name: load tailscale service
  ansible.builtin.command: launchctl load -w {{ tailscale_service_plist_path }}
  become: true
  changed_when: false
  listen: load tailscale service

- name: stop tailscale
  ansible.builtin.command: launchctl stop com.tailscale.tailscaled
  become: true
  changed_when: false
  listen: stop tailscale

- name: start tailscale
  ansible.builtin.command: launchctl start com.tailscale.tailscaled
  become: true
  changed_when: false
  listen: start tailscale
